### ISSUE TITLE
Error Or Bug In Console Related To Afk Manager

### ISSUE THREAD

**Issue by Superduash** [ExoBiTe/PlaytimeRewardsRewrite#1]
```
[14:22:48 WARN]: [PlaytimeRewards] Plugin PlaytimeRewards v0.2.0 generated an exception while executing task 66
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:?]
	at com.github.exobite.mc.playtimerewards.main.AFKManager$1.run(AFKManager.java:96) ~[PlaytimeRewards.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-160]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-160]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

What Error Is This? And How To Fix It.. It only occurs sometimes .. HALP! 😭

**Comment by ExoBiTe** [comment]
Hey there, thanks for the Bug Report. I've modified that Code, and this Error shouldn't happen anymore. But sadly i can't test it right now. 
I've uploaded it as a Pre-Release, you can try to test it if you want:
https://github.com/ExoBiTe/PlaytimeRewardsRewrite/releases/tag/v0.2.1pre

Please let me know if this Error still occurs, if you test it :)

**Comment by ExoBiTe** [comment]
As you didn't respond anymore, i'm gonna mark this as completed.
